name: ferric
version: 1.0
dependencies:
  - aeson
  - base
  - bytestring
  - http-conduit
  - template-haskell
  - zstd
default-extensions:
  - TemplateHaskell
  - TypeApplications
  - UnicodeSyntax
ghc-options:
  - -Wall
library:
  source-dirs: src
