name: ferric
version: 1.0
dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - free
  - http-conduit
  - linear-base
  - template-haskell
  - zstd
default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - LinearTypes
  - NamedFieldPuns
  - RecordWildCards
  - TemplateHaskell
ghc-options:
  - -Wall
  - -ddump-splices
  - -ddump-to-file
library:
  source-dirs: src
