name: ferric
version: 1.0
dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - http-conduit
  - template-haskell
  - zstd
  - pretty-simple
  - text
default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - TemplateHaskell
  - TypeApplications
ghc-options:
  - -Wall
library:
  source-dirs: src
  exposed-modules:
    - Ferric
